import type { Metadata } from "next";
import { Libre_Bodoni } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import ModelView from "@/components/ModelView";

const LibreBodoni = Libre_Bodoni({
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${LibreBodoni.className} antialiased`}>
        <div className="">
          <Navbar />
        </div>
        <div className="relative">
          <div id="scroll-proxy" className="w-full h-[300vh]">
            <div className="h-screen flex items-center justify-center">
              <ModelView />
            </div>
          </div>
          {children}

          <div className="h-screen bg-white flex items-center justify-center">
            <p className="text-4xl">Next section content</p>
          </div>
        </div>
      </body>
    </html>
  );
}
