import type { Metadata } from "next";
import { Libre_Bodoni } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const LibreBodoni = Libre_Bodoni({
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${LibreBodoni.className} antialiased`}
      > 
        <div className="">
          <Navbar/>
        </div>
        <div className="">
          {children}
        </div>
      </body>
    </html>
  );
}
