import type { Metadata } from "next";
import { Libre_Bodoni } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import ModelView from "@/components/ModelView";

const LibreBodoni = Libre_Bodoni({
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${LibreBodoni.className} antialiased`}>
        <div className="">
          <Navbar />
        </div>
        <div className="relative h-fit overflow-hidden">
          <div id="scroll-proxy" className="w-full absolute h-[300vh]">
            <div className="h-screen flex items-center justify-center relative">
              <ModelView />
            </div>
          </div>
          
          <div className="">
            {children}
          </div>
          
          <div className="bg-gray-500 min-h-50 w-full">
              hello
          </div>
        </div>
      </body>
    </html>
  );
}
